docs: création de la documentation CMS
DNUM-SocialGouv/1j1s-main-cms pull request #353
Opened 2024-07-24 15:46 UTC by LIG-OCTO

Création de la documentation Docusaurus sur le main CMS

2024-07-29 09:18 UTC, Mintoo200 requested changes
Quasiment tous les fichiers sont spécifique au front

2024-07-29 09:18 UTC, Mintoo200 commented on docs/docs/architecture/architecture.md
> +* `*.<interface>.service.ts` : Implémentation de l'interface `<interface>`. Ex : `tarteAuCitron.cookies.service.ts` est une implémentation de l'interface dans `cookies.service.ts`.
Tout ça, c'est spécifique au front

2024-08-01 08:09 UTC, Mintoo200 commented on docs/docs/convention/langages.md
> +* nommer la callback des useEffect
```suggestion
```

2024-08-01 08:10 UTC, Mintoo200 commented on docs/docs/convention/langages.md
> +```
```suggestion
```

2024-08-01 08:13 UTC, Mintoo200 commented on docs/docs/convention/langages.md
> +* tests end-to-end pour simuler un workflow complet utilisateur sur une fonctionnalité. Exemple : recherche d'une offre d'emploi puis consultation du détail d'une offre
```suggestion
Nous n'utilisons que des tests unitaires
```

2024-08-01 08:17 UTC, Mintoo200 commented on docs/docs/onboarding/fonctionnalites.md
Spécifique front

2024-08-01 08:18 UTC, Mintoo200 commented on docs/docs/onboarding/installation.md
Front only

2024-08-01 08:18 UTC, Mintoo200 commented on docs/docs/onboarding/prerequis.md
Front

2024-08-01 08:21 UTC, Mintoo200 commented on docs/docs/tuto/copie-donnee-en-local.md
> +Une désynchronisation entre le contenu indexé par Meilisearch et le contenu présent en base de données est donc quotidiennement présente. Pour résoudre le problème nous avons mis en place une solutio
C'est une procédure à part, ça ne devrait pas être dans le fichier `copie-donnee-en-local`

2024-08-01 08:24 UTC, Mintoo200 commented on docs/docs/tuto/resynchronisation-meilisearch-strapi.md
> +
Ça serait bien de mettre quelque part par ici un lien vers le problème des 10000 offres indexées max

2024-08-01 08:32 UTC, Mintoo200 commented on docs/docusaurus.config.js
> +								href: 'https://github.com/DNUM-SocialGouv/1j1s-main-cms',
```suggestion
								href: 'https://github.com/DNUM-SocialGouv/1j1s-front',
```

2024-08-01 08:34 UTC, Mintoo200 commented on docs/docusaurus.config.js
> +						to: './storybook',
```suggestion
						to: 'https://dnum-socialgouv.github.io/1j1s-front/storybook',
```

2024-08-09 10:45 UTC, LIG-OCTO commented on docs/docs/onboarding/installation.md
y'a une procédure d'install pour le CMS ?

2024-08-09 10:45 UTC, LIG-OCTO commented on docs/docs/tuto/copie-donnee-en-local.md
> +Une désynchronisation entre le contenu indexé par Meilisearch et le contenu présent en base de données est donc quotidiennement présente. Pour résoudre le problème nous avons mis en place une solutio
Pas sur de comprendre, à discuter ensemble

2024-08-21 08:20 UTC, Mintoo200 commented on docs/docs/onboarding/prerequis.md
> +```
```suggestion
---
sidebar_label: Prérequis d'installation
sidebar_position: 1
---

# Installation pour le développement sur 1j1s-main-cms

_20 Avril 2023_

## Introduction
Ce document relate les différents prérequis permettant l'installation du projet.

## Pré-requis

* [NodeJS](https://nodejs.org/fr/)
* [nvm](https://github.com/nvm-sh/nvm) recommandé
* [npm](https://www.npmjs.com/) 
* [Docker](https://docs.docker.com/desktop/)
* [docker-compose](https://docs.docker.com/compose/)

## Pour aller plus loin dans l'écosystème 1j1s (optionnel)

* [Projet chargement de données](https://github.com/DNUM-SocialGouv/1j1s-stage-orchestrateur-transform-load)
```

2024-08-21 08:21 UTC, Mintoo200 commented on docs/docs/onboarding/prerequis.md
En commentaire plus bas

2024-08-21 08:29 UTC, Mintoo200 commented on docs/docs/tuto/copie-donnee-en-local.md
> +Une désynchronisation entre le contenu indexé par Meilisearch et le contenu présent en base de données est donc quotidiennement présente. Pour résoudre le problème nous avons mis en place une solutio
Tu as un fichier dont le but est d'expliquer comment copier les données de la recette en local. La procédure pour fixer la synchro meilisearch est une procédure à part, il serait mieux d'avoir une page "Copier les données en local" **et** une page "Fixer la synchro" pour pouvoir retrouver les deux manip facilement plutôt qu'une seule page "Fixer la synchro" dont une des sous-partie est "copier les données en local"

2024-08-21 08:31 UTC, Mintoo200 approved these changes

2024-08-21 12:17 UTC, merged