chore: ajout script récupération données de recette
DNUM-SocialGouv/1j1s-main-cms pull request #72
Opened 2023-04-04 15:40 UTC by suli-octo

2023-04-04 17:11 UTC, Sefrancois approved these changes
😛

2023-04-05 07:57 UTC, gmoocto requested changes
Top ! Manque juste une petite update / nouvelle version du pour éviter le doublonnage du code du script 👀 : 
`docs/proc/20230302-copie-donnee-en-local.md`

2023-04-05 12:48 UTC, Naorid requested changes

2023-04-05 12:48 UTC, Naorid commented on docs/proc/copie-donnee-en-local.md
> +export SCALINGO_API_TOKEN='<la clef API de Scalingo>'
Je crois qu'il faut pas mettre de export vu que le script appelle déjà en faisant un export

2023-04-05 12:48 UTC, Naorid commented on docs/proc/copie-donnee-en-local.md
> +fi
Il faut copier ce code pour faire la meme chose avec le .env.docker j'ai l'impression.
Peut-etre que ca marchait chez toi parce que tu les avais export pendant le dev ? 🤔

2023-04-05 13:04 UTC, Naorid commented
J'aurai rajouté la commande dans le README

2023-04-05 13:18 UTC, gmoocto approved these changes

2023-04-05 14:53 UTC, suli-octo commented on docs/proc/copie-donnee-en-local.md
> +Cette clef (API Token) est à remplir dans la variable d'environnement `SCALINGO_API_TOKEN` dans `.env`.
bien vu ! du coup j'ai mis à jour le script

2023-04-05 14:53 UTC, suli-octo commented on docs/proc/copie-donnee-en-local.md
> +fi
justement on a dit qu'on ne mettait pas de token en clair, c'est pour ça qu'il faut passer par un .env qui est une copie du .env.docker, avec la bonne valeur pour SCALINGO_API_TOKEN :)

2023-04-05 15:20 UTC, suli-octo commented
@Naorid  > J'aurai rajouté la commande dans le README

Il y a le ticket évol de Guillaume qui l'a ajouté dans le readme du front, après on peut être le mettre dans le readme du CMS si c'est plus parlant

2023-04-05 15:32 UTC, Naorid approved these changes

2023-04-05 15:33 UTC, merged